import {test} from 'bun:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import path from 'node:path';
import {rewriteNativeAsset,NATIVE_ASSET_SOURCE_SHA,prepareReviewedNativeInputs,REVIEWED_PONYTAIL_MODULE,REVIEWED_AST_FILENAME} from '../native-runtime-assets.mjs';
const repository=path.resolve(import.meta.dirname,'../..'),core=await fs.realpath(path.join(repository,'node_modules/@opencode/core'));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
test('asset rewrites require exact pinned sources and embed only reviewed native paths',async()=>{
 const require=createRequire(path.join(core,'package.json'));
 const pty=await fs.readFile(path.join(core,'dist/chunks/credential-dajrwvna.js'));
 assert.equal(hash(pty),NATIVE_ASSET_SOURCE_SHA.pty);
 const assetPath=path.join(path.dirname(require.resolve('@opencode-ai/pty-darwin-arm64/package.json')),'bin/opencode-pty');
 const assetSha256=hash(await fs.readFile(assetPath));
 const transformed=rewriteNativeAsset('pty',pty,{assetPath,assetSha256});
 assert.match(transformed,/with \{type:'file'\}/);assert.match(transformed,/version:'0.1.13'/);assert.doesNotMatch(transformed,/binaryPath|createRequire/);
 const photon=await fs.readFile(require.resolve('@silvia-odwyer/photon-node'));
 const rewritten=rewriteNativeAsset('photon',photon);
 assert.match(rewritten,/globalThis.__OPENCODE_PHOTON_WASM_PATH/);assert.doesNotMatch(rewritten,/join\(__dirname, 'photon_rs_bg.wasm'\)/);
 assert.equal(rewritten.includes('new WebAssembly.Module(bytes)'),true);
 for(const kind of ['pty','photon']) assert.throws(()=>rewriteNativeAsset(kind,Buffer.from('changed source'),{assetPath,assetSha256}),/resolver changed/);
 assert.throws(()=>rewriteNativeAsset('pty',pty,{assetPath,assetSha256:'0'.repeat(64)}),/asset changed/);
});
test('reviewed original closure and exact constructor transforms are inventoried without runtime cache roots',async()=>{
 const reviewed=await prepareReviewedNativeInputs(repository);
 const root=path.join(repository,'packages/web/runtime/reviewed-inputs');
 const manifest=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));
 for(const input of manifest.inputs)for(const file of input.files)assert.equal(reviewed.inputFiles.get(path.join(root,input.id,file.path)),file.sha256);
 assert.equal(reviewed.inputFiles.has(path.join(root,'slim-2.2.25/dist/server/index.d.ts')),true);
 assert.equal(reviewed.inputFiles.has(path.join(root,'ponytail-4.10.0/LICENSE')),true);
 const slim=reviewed.rewrites.get(path.join(root,'slim-2.2.25/dist/server/index.js'));
 assert.match(slim,/v1Hooks = await requireReviewedSlimHost\(directory\)\.hooks\(pluginInput\)/);
 assert.doesNotMatch(slim,/v1Hooks = await OhMyOpenCodeLite\(pluginInput\)/);
 assert.match(slim,/function createAutoUpdateCheckerHook\(ctx, options = \{\}\) \{\s+return \{ event: async \(\) => \{\} \};/);
 assert.equal(reviewed.transforms.find(item=>item.reason==='reviewed-slim-owned-constructor-seams').steps.length,36);
 assert.match(reviewed.virtualModules.get(REVIEWED_PONYTAIL_MODULE),/^export default /);
 assert.equal(reviewed.claudeCredentials.path,'DevRyan-Claude-credentials.mjs');
 assert.equal(reviewed.claudeCredentials.sha256,hash(reviewed.claudeCredentials.contents));
 assert.equal(reviewed.claudeCredentials.mode,0o644);
 assert.match(reviewed.claudeCredentials.contents,/export \{createPlatformCredentialStore, ensureFreshToken, refreshOAuthToken\};/);
 assert.equal(reviewed.ast.path,REVIEWED_AST_FILENAME);
 assert.equal(reviewed.ast.sha256,hash(await fs.readFile(reviewed.ast.source)));
 assert.equal(reviewed.provenance.find(value=>value.id==='ast-grep-0.45.3').license.standaloneLicenseCaptured,false);
 assert.equal(reviewed.provenance.find(value=>value.id==='jsdom-30.1.1').version,'30.1.1');
 const domRoot=path.join(root,'jsdom-30.1.1/node_modules/jsdom/lib/jsdom');
 assert.match(reviewed.rewrites.get(path.join(domRoot,'utils.js')),/exports.Canvas = null;/);
 assert.doesNotMatch(reviewed.rewrites.get(path.join(domRoot,'utils.js')),/require\("canvas"\)/);
 assert.doesNotMatch(reviewed.rewrites.get(path.join(domRoot,'living/css/helpers/computed-style.js')),/const defaultStyleSheet = fs.readFileSync/);
 assert.equal(reviewed.resolutions.has(path.join(domRoot,'browser/Window.js')+'\0whatwg-url'),true);
 const jsoncMain=Bun.resolveSync('jsonc-parser',path.join(repository,'packages/web'));
 const jsoncPackage=path.resolve(path.dirname(jsoncMain),'../../package.json');
 assert.equal(reviewed.inputFiles.get(jsoncPackage),hash(await fs.readFile(jsoncPackage)));
 assert.equal(reviewed.transforms.find(item=>item.reason==='pinned-jsonc-original-esm-module-resolution').sha256,hash(await fs.readFile(jsoncMain)));
 assert.equal([...reviewed.inputFiles].every(([file])=>file.startsWith(root+path.sep)||file===jsoncPackage||file===path.join(repository,'packages/web/server/default-config/plugins/devryan-document-reader.mjs')||file===path.join(repository,'packages/web/server/default-config/plugins/devryan-document-reader.d.mts')||file===path.join(repository,'packages/web/server/default-config/plugins/devryan-browser.mjs')||file===path.join(repository,'packages/web/server/default-config/plugins/devryan-browser.d.mts')),true);
});
