import type { RegistrationCapability, RegistrationOrigin } from './registration-origin.js';

/** Exact PluginInternal pre/post inventory reviewed from @opencode/core 2.0.24. */
export const NATIVE_PLUGIN_VERSION = '2.0.24';
export const REVIEWED_NATIVE_PLUGIN_IDS: readonly string[] = Object.freeze([
  'opencode.tool.input.repair',
  'opencode.config.worktree',
  'opencode.browser',
  'opencode.config.mcp',
  'opencode.mcp.codemode.defaults',
  'opencode.wellknown',
  'opencode.vcs.git',
  'opencode.agent',
  'opencode.plan',
  'opencode.command',
  'opencode.skill',
  'opencode.vcs.hg',
  'opencode.models.dev',
  'opencode.provider.amazon.bedrock',
  'opencode.provider.azure',
  'opencode.provider.cerebras',
  'opencode.provider.chatgpt',
  'opencode.provider.cloudflare.ai.gateway',
  'opencode.provider.cloudflare.workers.ai',
  'opencode.provider.cohere',
  'opencode.provider.digitalocean',
  'opencode.provider.dynamic',
  'opencode.provider.gateway',
  'opencode.provider.github.copilot',
  'opencode.provider.gitlab',
  'opencode.provider.google.vertex',
  'opencode.provider.kilo',
  'opencode.provider.llmgateway',
  'opencode.provider.lmstudio',
  'opencode.provider.modal',
  'opencode.provider.nvidia',
  'opencode.provider.ollama',
  'opencode.provider.openai',
  'opencode.provider.snowflake.cortex',
  'opencode.provider.opencode',
  'opencode.provider.openrouter',
  'opencode.provider.perplexity',
  'opencode.provider.poe',
  'opencode.provider.prompt-cache-key',
  'opencode.provider.sap.ai.core',
  'opencode.provider.vercel',
  'opencode.provider.venice',
  'opencode.provider.vllm',
  'opencode.provider.xai',
  'opencode.provider.zenmux',
  'opencode.websearch.exa',
  'opencode.websearch.firecrawl',
  'opencode.websearch.parallel',
  'opencode.websearch.tavily',
  'opencode.websearch.tinyfish',
  'opencode.tool.patch',
  'opencode.prompt.openai',
  'opencode.prompt.anthropic',
  'opencode.prompt.kimi',
  'opencode.prompt.arcee',
  'opencode.prompt.meta',
  'opencode.prompt.verbosity',
  'opencode.prompt.identity',
  'opencode.tool.edit',
  'opencode.tool.glob',
  'opencode.tool.grep',
  'opencode.tools',
  'opencode.tools.mcp-resources',
  'opencode.tool.question',
  'opencode.tool.read',
  'opencode.tool.shell',
  'opencode.tool.skill',
  'opencode.tool.subagent',
  'opencode.tool.webfetch',
  'opencode.tool.websearch',
  'opencode.tool.write',
  'opencode.warming',
  'opencode.config.instruction',
  'opencode.config.reference',
  'opencode.config.agent',
  'opencode.config.command',
  'opencode.config.compaction',
  'opencode.config.formatter',
  'opencode.config.image',
  'opencode.config.location-watcher',
  'opencode.config.shell',
  'opencode.config.snapshot',
  'opencode.config.tool-output',
  'opencode.config.compatibility',
  'opencode.config.skill',
  'opencode.config.provider',
  'opencode.config.websearch',
  'opencode.config.policy',
]);
const toolCapabilities: Readonly<Record<string, readonly RegistrationCapability[]>> = Object.freeze({
  'opencode.tool.read': ['read'], 'opencode.tool.glob': ['read'], 'opencode.tool.grep': ['read'],
  'opencode.tool.skill': ['read'], 'opencode.tool.write': ['write'], 'opencode.tool.edit': ['write'],
  'opencode.tool.patch': ['write'], 'opencode.tool.shell': ['process'],
  'opencode.tool.subagent': [], 'opencode.tool.webfetch': ['network'], 'opencode.tool.websearch': ['network'],
  'opencode.browser': [], 'opencode.tools.mcp-resources': [], 'opencode.tools': [],
  'opencode.tool.question': ['control'],
});
export function createReviewedNativePluginRegistry(manifestDigest: string, options: { readonly disableTools?: boolean; readonly hostDigest?: string } = {}): ReadonlyMap<string, RegistrationOrigin> {
  if (!/^[a-f0-9]{64}$/.test(manifestDigest)) throw new TypeError('native manifest digest must be SHA-256');
  const registry = new Map<string, RegistrationOrigin>(REVIEWED_NATIVE_PLUGIN_IDS.map((id) => [id, Object.freeze({
    kind: 'native', id, manifestDigest, capabilities: Object.freeze(options.disableTools ? [] :
      [...(toolCapabilities[id] ?? (id.startsWith('opencode.provider.') ? ['provider'] : ['control']))]),
  })]));
  if (options.hostDigest !== undefined) {
    if (!/^[a-f0-9]{64}$/.test(options.hostDigest)) throw new TypeError('native host digest must be SHA-256');
    registry.set('devryan.remote-mcp', Object.freeze({ kind: 'native', id: 'devryan.remote-mcp',
      manifestDigest: options.hostDigest, capabilities: Object.freeze(options.disableTools ? [] : ['network', 'control'] as const) }));
  }
  return registry;
}
